config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :patrons
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patron.rb
class Patron < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController

  def index
    @patrons = Patron.all
  end

  def create
    @patron = Patron.new(patron_params)

    @patron.save
    redirect_to @patron
  end

  def show
    @patron = Patron.find(params[:id])
  end

  def new
  end

  private
  def patron_params
    params.require(:patron).permit(:firstname, :lastname, :email, :address, :loaves)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patrons_helper.rb
module PatronsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZimmermansFull</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patrons/index.html.erb
<h1>Patron List</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Number of Roasts</th>
    <th></th>
  </tr>

  <% @patrons.each do |patron| %>
    <tr>
      <td><%= patron.firstname %></td>
      <td><%= patron.lastname %></td>
      <td><%= patron.email %></td>
      <td><%= patron.address %></td>
      <td><%= patron.loaves %></td>
      <td><%= link_to 'Show', patron_path(patron) %></td>
    </tr>
  <% end %>
</table>

app/views/patrons/new.html.erb
<h1> New Patron Order </h1>

<%= form_with scope: :patron, url: patrons_path, local: true do |form| %>
  <p>
    <%= form.label :firstname %><br>
    <%= form.text_field :firstname %>
  </p>
  <p>
    <%= form.label :lastname %><br>
    <%= form.text_field :lastname %>
  </p>
  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </p>

  <p>
    <%= form.label :loaves %><br>
    <%= form.text_field :loaves %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/patrons/show.html.erb
<p> First Name: <%= @patron.firstname %> </p>
<p> Last Name:<%= @patron.lastname %> </p>
<p> Email: <%= @patron.email %> </p>
<p> Address:<%= @patron.address %> </p>
<p> Number of Roasts: <%= @patron.loaves %> </p>